#pragma once
//
// Success codes
//
 

#include <ntifs.h>
#include <ntimage.h>
#include <intrin.h>
#include <minwindef.h>
#include <xmmintrin.h>
 

#include "macros.h"
#include "types.h"
#include "data_types.h"
#include "../ia32/ia32.hpp"
#include "ntos_struct_def.h"
#include "native_api.h"
#include "internal_function_defs.h"
#include "kvector.h"
#include "math_utils.h"
#include "string_utils.h"
#include "module_info.h"
#include "os_info.h"
#include "process_utils_struct.h"
#include "windows_version_enum.h"
#include "xor_crypt.h"
#include "import_encrypt.h"
#include "comm_utils.h"
#include "hook_manager.h"
#include "hook_functions.h"
#include "signature_scanner.h"
#include "scanner_fun.h"
#include "scanner_offset.h"
#include "hidden_module_list.h"
#include "hook_manager.h"
#include "process_manager_utils.h"
#include "inject_utils.h"
#include "hook_functions.h"
#include "internal_function_defs.h"
#include "feature_data_initializer.h"
#include "scanner_data.h"
#include "kernel_hide_utils.h"
#include "memory_utils.h"
#include "process_utils.h"
#include "feature_offset_initializer.h"
 
 

#include "time_utils.h"
#include "cpu_registers.h"
#include "thread_utils.h"
#include "vfun_utils.h"
#include "user_call_utils.h"
#include "sstd_utils.h"
#include "hidden_user_memory_list.h"
#include "fault_uitls.h"
#include "user_comm\user_comm_struct.h"
#include "user_comm\user_comm.h"
#include "auth.h"
#include "file_utils.h"
#include "log_utils.h"
#include "global_initializer.h"
#include "khyper_vt.h"
#include "driver_feature_init.h"
#include "hook_utils.h"
#include "shadow_break_point.h"
#include "hook_mem_protection.h"
#include "hook_process_manager.h"
#include "hook_user_comm.h"
#include "kernel_dwm_drawing.h"
#include "render.h"
#include "memory_pool.h"
#include "call_back_utils.h"
#include "kernel_hide_utils.h"
#include "math.h"
#include "font_utils.h"
#include "pmcol.h"
#include "dx11.h"
#include "fontdata.h"
#include "LegacyRender.h"
#include "mouse_class_utils.h"
#include "key_board_class.h"
#include "../game/game_cheat_config.h"
#include "../game/delta_force.h"
#include "../game/game_cheat.h"
 
 
#include "VMProtectDDK.h"
#include "../LDE64.h"

#include "../vtx/hv_defs.h"
#include "../vtx/vmcs_encodings.h"
#include "../vtx/mtrr.h"
#include "../vtx/poolmanager.h"
#include "../vtx/ept.h"
#include "../vtx/page-tables.h"
#include "../vtx/hv_vt_structs.h"
#include "../vtx/exception.h"
#include "../vtx/cpuid.h"
#include "../vtx/msr.h"
#include "../vtx/xsave.h"
#include "../vtx/segment.h"
#include "../vtx/vm_intrin.h"
#include "../vtx/vm_context.h"
#include "../vtx/compatibility_checks.h"
#include "../vtx/vt_global.h"
#include "../vtx/invalidators.h"
#include "../vtx/exception-routines.h"
#include "../vtx/gdt.h"
#include "../vtx/idt.h"
#include "../vtx/interrupt.h"
#include "../vtx/interrupt-handlers.h"
#include "../vtx/spinlock.h"
#include "../vtx/allocators.h"
#include "../vtx/timing.h"
#include "../vtx/mm.h"
#include "../vtx/processor_affinity.h"
#include "../vtx/hypercalls.h"
#include "../vtx/hv_pre_vmcall.h"
#include "../vtx/hypervisor_routines.h"
#include "../vtx/vmcs_utils.h"
#include "../vtx/vmcs.h"
#include "../vtx/vmm.h"
#include "../vtx/vmexit_handler.h"
#include "../vtx/vmcall_handler.h"




